apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-end
  namespace: backend    # <--- make sure to add the namespace here
  labels:
    app: backend-end
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-end
  template:
    metadata:
      labels:
        app: backend-end
    spec:
      containers:
      - name: jokes-bakend
        image: loka07/jokes-bakend:v2
        ports:
        - containerPort: 3000
        env:
        - name: DB_HOST
          value: mysql.database.svc.cluster.local
        - name: DB_DATABASE
          valueFrom:
            configMapKeyRef:
              name: mysql-config
              key: database
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: username
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: password
