apiVersion: v1
kind: Service
metadata:
  name: backend-end-service
  namespace: backend
spec:
  selector:
    app: backend-end
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
  type: ClusterIP
