version: '3.8'
services:
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
    volumes:
      - mysql-data:/var/lib/mysql
      - ./backend/jokes.sql:/docker-entrypoint-initdb.d/jokes.sql
    ports:
      - "3306:3306"

  backend:
    build: ./backend
    depends_on:
      - mysql
    ports:
      - "3000:3000"

  frontend:
    image: nginx:alpine
    volumes:
      - ./frontend:/usr/share/nginx/html
    ports:
      - "8080:80"

volumes:
  mysql-data:

