apiVersion: v2
name: joke-app
description: A parent Helm chart for the Joke Generator microservices
type: application
version: 0.1.0
appVersion: "1.0"

dependencies:
  - name: frontend
    version: 0.1.0
    repository: "file://charts/frontend"
  - name: backend
    version: 0.1.0
    repository: "file://charts/backend"
  - name: db
    version: 0.1.0
    repository: "file://charts/db"
