apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: front-end
  name: front-end
  namespace: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: front-end
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: front-end
    spec:
      containers:
      - image: loka07/jokes-frontend:latest
        name: jokes-frontend
        resources: {}
        ports:
        - containerPort: 80
status: {}
