apiVersion: v1
kind: Service
metadata:
  name: front-end-service
  namespace: jokes-app
spec:
  selector:
    app: front-end
  ports:
  - protocol: TCP
    port: 80       # Service port
    targetPort: 80 # Pod/container port
  type: ClusterIP
