apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mysql.serviceName }}
  namespace: {{ .Values.app.namespace }}
  labels:
    app: {{ .Values.mysql.labels.app }}
spec:
  clusterIP: None
  selector:
    app: {{ .Values.mysql.labels.app }}
  ports:
    - port: {{ .Values.mysql.container.port }}
