# .github/workflows/deploy-helm.yaml
name: "Helm Install: External Secrets"

on:
  workflow_dispatch:
    

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: us-east-1

jobs:
  install-helm:
    name: "Install External Secrets via Helm"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install AWS CLI, kubectl, and Helm
        run: |
          sudo apt-get update -y
          sudo apt-get install -y curl unzip jq
          curl -sLo awscliv2.zip https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip || exit 1
          unzip -q awscliv2.zip || exit 1
          sudo ./aws/install || exit 1
          curl -LO "https://dl.k8s.io/release/$(curl -Ls https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl" || exit 1
          chmod +x kubectl && sudo mv kubectl /usr/local/bin/ || exit 1
          curl -fsSL https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash || exit 1

      - name: Configure kubeconfig for EKS
        run: |
          aws eks update-kubeconfig --region us-east-1 --name Jokes-demo || exit 1

      - name: Install External Secrets via Helm
        run: |
          helm repo add external-secrets https://charts.external-secrets.io || exit 1
          helm repo update || exit 1
          helm upgrade --install external-secrets external-secrets/external-secrets \
            --namespace external-secrets \
            --create-namespace || exit 1
