name: "Helm Install: External Secrets"

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Terraform Infrastructure Change Management Pipeline with GitHub Actions"]
    types:
      - completed

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: us-east-1

jobs:
  install-helm:
    if: github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success'
    name: "Install External Secrets via Helm"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install AWS CLI, kubectl, and Helm
        run: |
          sudo apt-get update -y
          sudo apt-get install -y curl unzip jq
          curl -sLo awscliv2.zip https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip
          unzip -q awscliv2.zip
          sudo ./aws/install --update
          curl -LO "https://dl.k8s.io/release/$(curl -Ls https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x kubectl && sudo mv kubectl /usr/local/bin/
          curl -fsSL https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

      - name: Configure kubeconfig for EKS
        run: |
          aws eks update-kubeconfig --region us-east-1 --name Jokes-demo

      - name: Patch EBS CSI Add-on to use IRSA role
        run: |
          echo "Patching EBS CSI add-on with IRSA role..."
          aws eks update-addon \
            --cluster-name Jokes-demo \
            --addon-name aws-ebs-csi-driver \
            --service-account-role-arn arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/Jokes-demo-ebs-csi-controller-role \
            --region us-east-1 \
            --resolve-conflicts OVERWRITE


      - name: Install External Secrets via Helm
        run: |
          helm repo add external-secrets https://charts.external-secrets.io
          helm repo update
          helm upgrade --install external-secrets external-secrets/external-secrets \
            --namespace external-secrets \
            --create-namespace \
            --wait

      - name: Restart the EBS CSI pods
        run: |
          kubectl rollout restart deployment ebs-csi-controller -n kube-system
          kubectl rollout restart daemonset ebs-csi-node -n kube-system
