name: Deploy Helm Chart to EKS

on:
  push:
    branches:
      - helm-implement
    paths:
      - 'joke-app/**'
      - '.github/workflows/deploy.yaml'

  workflow_dispatch:

env:
  AWS_REGION: us-east-1  # adjust this
  CLUSTER_NAME: Jokes-demo  # adjust this
  NAMESPACE: jokes-app  # adjust this
  RELEASE_NAME: joke-app

jobs:
  helm-deploy:
    name: Deploy Helm Chart
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Set up kubeconfig for EKS
        run: |
          aws eks update-kubeconfig --region $AWS_REGION --name $CLUSTER_NAME

      - name: Set up Helm
        uses: azure/setup-helm@v3

      - name: Helm Lint
        run: helm lint ./joke-app

      - name: Helm Dry Run
        run: helm upgrade --install $RELEASE_NAME ./joke-app \
          --namespace $NAMESPACE \
          --create-namespace \
          --dry-run --debug

      - name: Deploy with Helm
        run: helm upgrade --install $RELEASE_NAME ./joke-app \
          --namespace $NAMESPACE \
          --create-namespace \
          --values ./joke-app/values.yaml \
          --wait

      - name: Wait for Deployment to be Ready
        run: |
          kubectl rollout status deployment/$RELEASE_NAME -n $NAMESPACE --timeout=120s
