name: "Terraform Infrastructure Change Management Pipeline with GitHub Actions"

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Terraform action to perform'
        required: true
        default: 'plan'
        type: choice
        options:
          - plan
          - apply

env: 
  TF_LOG: INFO
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  terraform:
    name: "Terraform Infra - Plan or Apply"
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./INFRA/eks-install    

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.0

      - name: Download terraform.tfvars from S3
        run: |
          aws s3 cp s3://shakthi-tf-bucket/terraform.tfvars terraform.tfvars

      - name: Terraform init
        run: terraform init

      - name: Terraform format
        run: terraform fmt -check

      - name: Terraform validate
        run: terraform validate

      - name: Terraform Plan (generate tfplan + tfplan.txt)
        if: github.event.inputs.action == 'plan'
        run: |
          terraform plan -no-color -input=false -lock-timeout=60s -out=tfplan
          terraform show -no-color tfplan > tfplan.txt

      - name: Upload tfplan & tfplan.txt as artifact
        if: github.event.inputs.action == 'plan'
        uses: actions/upload-artifact@v4
        with:
          name: terraform-plan
          path: |
            ./INFRA/eks-install/tfplan
            ./INFRA/eks-install/tfplan.txt
          retention-days: 1
          if-no-files-found: error
          compression-level: 6
          overwrite: false
          include-hidden-files: false

      - name: Terraform Apply (auto-approve)
        if: github.event.inputs.action == 'apply'
        run: terraform apply --auto-approve
