name: "Terraform Infrastructure Change Management Pipeline with GitHub Actions"

on: 
  push: 
    branches:
      - frontend-config
    paths:
      - INFRA/eks-install**
      - .github/workflows/**

  workflow_dispatch:
    inputs:
      action:
        description: 'Terraform action to perform'
        required: true
        default: 'plan'
        type: choice
        options:
          - plan
          - apply

env: 
  TF_LOG: INFO
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  terraform:
    name: "Terraform Infra - Plan or Apply"
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./INFRA/eks-install    

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.0

      - name: Download terraform.tfvars from S3
        run: |
          aws s3 cp s3://shakthi-tf-bucket/terraform.tfvars terraform.tfvars

      - name: Terraform init
        id: init
        run: terraform init

      - name: Terraform format
        id: fmt
        run: terraform fmt -check

      - name: Terraform validate
        id: validate
        run: terraform validate

      - name: Terraform Plan (saved to tfplan)
        if: github.event.inputs.action == 'plan'
        run: terraform plan -out=tfplan

      - name: Upload tfplan artifact
        if: github.event.inputs.action == 'plan'
        uses: actions/upload-artifact@v4
        with:
          name: tfplan
          path: ./INFRA/eks-install/tfplan
                ./INFRA/eks-install/plan.txt

      - name: Download tfplan artifact
        if: github.event.inputs.action == 'apply'
        uses: actions/download-artifact@v4
        with:
          name: tfplan
          path: ./INFRA/eks-install

      - name: Terraform Apply (manual)
        if: github.event.inputs.action == 'apply'
        run: terraform apply tfplan
